#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: c1050fe
#
Name     : flnet
Version  : 7.5.0
Release  : 11
URL      : https://sourceforge.net/projects/fldigi/files/flnet/flnet-7.5.0.tar.gz
Source0  : https://sourceforge.net/projects/fldigi/files/flnet/flnet-7.5.0.tar.gz
Summary  : Library to access network sites using https protocol
Group    : Development/Tools
License  : GPL-2.0
Requires: flnet-bin = %{version}-%{release}
Requires: flnet-data = %{version}-%{release}
Requires: flnet-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : fltk-dev
BuildRequires : fontconfig-dev
BuildRequires : libXcursor-dev
BuildRequires : libXft-dev
BuildRequires : libXrender-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-file-errors.patch

%description
Flnet provides the Amateur Radio Net Control Station operator with a real
time tool to assist him or her in managing the net activities.  A single
screen with multiple windows is used to allow rapid entry, search, pick
and display of all stations calling in to the net.  All operations on
the main screen are accomplished with keyboard entries only.  No mouse
action is required to perform the net control functions.  Experience
has shown that most net control operators prefer this method of operation
to improve the speed of entry and selection

%package bin
Summary: bin components for the flnet package.
Group: Binaries
Requires: flnet-data = %{version}-%{release}
Requires: flnet-license = %{version}-%{release}

%description bin
bin components for the flnet package.


%package data
Summary: data components for the flnet package.
Group: Data

%description data
data components for the flnet package.


%package license
Summary: license components for the flnet package.
Group: Default

%description license
license components for the flnet package.


%prep
%setup -q -n flnet-7.5.0
cd %{_builddir}/flnet-7.5.0
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701956442
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static --enable-debug
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701956442
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flnet
cp %{_builddir}/flnet-%{version}/COPYING %{buildroot}/usr/share/package-licenses/flnet/b47456e2c1f38c40346ff00db976a2badf36b5e3 || :
cp %{_builddir}/flnet-%{version}/src/mbedtls/LICENSE %{buildroot}/usr/share/package-licenses/flnet/941df1b3181ce17b8441e0e3775808f266a80fc8 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/flnet

%files data
%defattr(-,root,root,-)
/usr/share/applications/flnet.desktop
/usr/share/pixmaps/flnet.xpm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flnet/941df1b3181ce17b8441e0e3775808f266a80fc8
/usr/share/package-licenses/flnet/b47456e2c1f38c40346ff00db976a2badf36b5e3
